# Generated by Django 4.1.1 on 2022-09-16 11:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name="User's first name")),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name="User's last name")),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographic')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date of birth')),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('\\d{11}', 'Minimum 11', code='invalid')], verbose_name='Phone')),
                ('balance', models.IntegerField(default=0)),
                ('person_disc', models.IntegerField(default=0)),
            ],
        ),
    ]
