# Generated by Django 4.1.1 on 2022-09-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CART', 'In cart'), ('AWAITING_ARRIVAL', 'Awaiting_arrival'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('AWAITING_DELIVERY', 'Awaiting delivery'), ('SENT', 'Sent'), ('FINISHED', 'Finished')], default='CART', max_length=50, verbose_name='State')),
                ('orders_id', models.CharField(blank=True, max_length=250, null=True, verbose_name="Order's id")),
                ('warranty_days', models.IntegerField(default=30, verbose_name='Dates of warranty')),
                ('orders_time', models.DateTimeField(blank=True, null=True, verbose_name='Orders date time field')),
                ('city', models.CharField(default='12345', max_length=100, verbose_name='Delivery city')),
                ('address', models.CharField(default='12345', max_length=250, verbose_name='Delivery address')),
                ('total_orders_price', models.IntegerField(blank=True, null=True, verbose_name='Total price of order')),
                ('fk_self', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
