# Generated by Django 4.0.7 on 2022-09-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_purchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='fk_self',
        ),
    ]
