# Generated by Django 4.1.1 on 2022-09-16 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('price', models.IntegerField(default=200, verbose_name='Price')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=50, verbose_name="Tag's title")),
                ('tag_description', models.CharField(max_length=100, verbose_name="Tag's description")),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('date_of_release', models.DateField(default=datetime.date.today, verbose_name='Date of release')),
            ],
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
            ],
            bases=('main.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='main.tag', verbose_name='tags'),
        ),
    ]
