# Generated by Django 4.0.7 on 2022-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_description',
            field=models.CharField(max_length=400, verbose_name="Tag's description"),
        ),
    ]
